### ISSUE TITLE
Remove deprecated 'parameter` function

### ISSUE THREAD

**Issue by stefankoppier** [Mr-Mappie/mappie#101]
**Is your feature request related to a problem? Please describe.**
The parameter reference function `parameter(String)` is deprecated and replaced by `to(String)` as it can refer to both a constructor parameter or a target property.

**Describe the solution you'd like**
Remove the deprecated `parameter(String)` function.

**Comment by TheMarvelFan** [comment]
Hi,

Is anyone working on this issue?
If not, I would like to take it up.

Thanks!

**Comment by stefankoppier** [comment]
Hi @TheMarvelFan, feel free to address this issue!

If you finish this issue, please update the website documentation and changelog with a reference to the issue (similar to the other entries), if no entry currently exist. You can use 'tbd' and 0.9.0 as the date.

**Comment by TheMarvelFan** [comment]
Hi @stefankoppier ,

I have made the changes required, and updated the website documentation as well. Please review the changes and let me know if any modifications are required!

I would also like to request you to merge these changes on or after October 1 for making this PR count as a valid Hacktoberfest contribution.

Thanks!

**Comment by TheMarvelFan** [comment]
Hi @stefankoppier  ,

Hacktoberfest has now started accepting contributions, so this PR can be merged now.
But, it is not detecting my PR for this issue as a part of Hacktoberfest. This is most probably because of the label of 'hacktoberfest' on this issue needs to start with a captial 'H', i.e., 'Hacktoberfest'.
Once this is done, I think it will detect my PR, and it can then be merged.

Thanks!

**Comment by stefankoppier** [comment]
The documentation on the hacktoberfest page state that it needs to be in lowercase. However, `hacktoberfest-accepted` should be the PR label. Maybe you can recreate the PR, and I will add the accepted label.

**Comment by TheMarvelFan** [comment]
@stefankoppier ok I will recreate the PR

**Comment by TheMarvelFan** [comment]
@stefankoppier 

I have recreated the PR. Please do the needful.

Thanks!
