### ISSUE TITLE
Add multiplatform support

### ISSUE THREAD

**Issue by sureshg** [Mr-Mappie/mappie#88]
This library looks nice and ergonomic. Please make it multiplatform. Currently, I can't use this in a shared project which targets JS/WASM and Native.

**Comment by stefankoppier** [comment]
Thanks for the issue. It's a fairly simple but great addition, so I'll make sure it'll be included in the next release. You're also welcome to add support for those targets. if you have the time.

**Comment by stefankoppier** [comment]
@sureshg I've created a PR. I've validated with a JS project, are you able to validate the branch if the targets work for your project? (i.e. publishToMavenLocal and import the 0.8.0-SNAPSHOT version in your project)

**Comment by sureshg** [comment]
@stefankoppier Thanks for working on this... don't we need to add all [these targets](https://github.com/JavierSegoviaCordoba/kopy/pull/30/files#diff-705e427349c44150d290b2bf2ef5c5311c4e0db7e36c7e42b790d43cb2f1803cR38-R51) for complete multiplatform support? My projects need Linux and macos targets

**Comment by stefankoppier** [comment]
Hi @sureshg, sorry for the delay and thanks for the example. I added most of them, including linux and mac. Could you take another look?
